#!/bin/sh

# Remove files generated by all projects.
rm -fv condor.log
rm -fv condor.out
rm -fv condor.err
rm -fv hw.tar.gz

# Remove folders generated by this project:


# Remove files generated by this project:
rm -fv *.out
